### PR TITLE
Stay away from Nan 2.0.0 :)

### PR DESCRIPTION
**Pull request by ghost**
Maybe related to #12

### CODE REVIEW

**Comment by akaustel** [comment]
@dropfen should you close this pull request to lessen confusion, if we agreed to use PR #14?

**Comment by dropfen** [comment]
I let them decide, they are smart enough, to not get confused, about 2 lines of package.json :D
Otherwise, I don’t think, it’s a good idea to use this package at all :D

**Comment by akaustel** [comment]
I don't question their intelligence, merely suggesting to reduce the work required to get it done.

**Comment by akaustel** [comment]
This can now be closed I suppose @dutow?

**Comment by akaustel** [comment]
@dutow sorry, was not meant for you, my bad. @dropfen or @adamansky can close this.

**Pull request closed without merging**
